#ifndef LIBPRCPP_CONFIG_H
#define LIBPRCPP_CONFIG_H

#ifndef PROJECT_BUILD_STATUS
    // 0:undefined 1:debug 2:staging 3:demo 4:release
    #define PROJECT_BUILD_STATUS @PROJECT_BUILD_STATUS@
#endif // PROJECT_BUILD_STATUS

#ifndef PROJECT_BUILD_TARGET
    // 0:undefined 1:linux 2:windows 3:osx 4:android 5:ios 6:web 7:ps 8:xbox 9:nintendo
    #define PROJECT_BUILD_TARGET @PROJECT_BUILD_TARGET@
#endif // PROJECT_BUILD_TARGET

#ifndef PROJECT_BUILD_COMPILER_ID
    // 0:undefined 1:GNU 2:MSVC 3:[Cc]lang
    #define PROJECT_BUILD_COMPILER_ID @PROJECT_BUILD_COMPILER_ID@
#endif // PROJECT_BUILD_COMPILER_ID

#ifndef LIBPRCPP_PROJECT_USING_JSONCPP
    #define LIBPRCPP_PROJECT_USING_JSONCPP @LIBPRCPP_PROJECT_USING_JSONCPP@
#endif // LIBPRCPP_PROJECT_USING_JSONCPP

#ifndef LIBPRCPP_PROJECT_USING_OPENSSL
    #define LIBPRCPP_PROJECT_USING_OPENSSL @LIBPRCPP_PROJECT_USING_OPENSSL@
#endif // LIBPRCPP_PROJECT_USING_OPENSSL

#ifndef LIBPRCPP_PROJECT_USING_DROGON_FRAMEWORK
    #define LIBPRCPP_PROJECT_USING_DROGON_FRAMEWORK @LIBPRCPP_PROJECT_USING_DROGON_FRAMEWORK@
#endif // LIBPRCPP_PROJECT_USING_DROGON_FRAMEWORK

#ifndef LIBPRCPP_PROJECT_USING_CRYPTOPP_CMAKE
    #define LIBPRCPP_PROJECT_USING_CRYPTOPP_CMAKE @LIBPRCPP_PROJECT_USING_CRYPTOPP_CMAKE@
#endif // LIBPRCPP_PROJECT_USING_CRYPTOPP_CMAKE

#ifndef LIBPRCPP_PROJECT_USING_SCYLLADB
    #define LIBPRCPP_PROJECT_USING_SCYLLADB @LIBPRCPP_PROJECT_USING_SCYLLADB@
#endif // LIBPRCPP_PROJECT_USING_SCYLLADB

#ifndef LIBPRCPP_PROJECT_USING_JWT_CPP
    #define LIBPRCPP_PROJECT_USING_JWT_CPP @LIBPRCPP_PROJECT_USING_JWT_CPP@
#endif // LIBPRCPP_PROJECT_USING_JWT_CPP

#ifndef LIBPRCPP_PROJECT_USING_LIBHARU
    #define LIBPRCPP_PROJECT_USING_LIBHARU @LIBPRCPP_PROJECT_USING_LIBHARU@
#endif // LIBPRCPP_PROJECT_USING_LIBHARU

#ifndef PROJECT_CPP_STANDARD
    #define PROJECT_CPP_STANDARD @PROJECT_CPP_STANDARD@
#endif // PROJECT_CPP_STANDARD

#ifndef LIBPRCPP_VERSION_MAJOR
    #define LIBPRCPP_VERSION_MAJOR @LIBPRCPP_VERSION_MAJOR@
#endif // LIBPRCPP_VERSION_MAJOR

#ifndef LIBPRCPP_VERSION_MINOR
    #define LIBPRCPP_VERSION_MINOR @LIBPRCPP_VERSION_MINOR@
#endif // LIBPRCPP_VERSION_MINOR

#ifndef LIBPRCPP_VERSION_PATCH
    #define LIBPRCPP_VERSION_PATCH @LIBPRCPP_VERSION_PATCH@
#endif // LIBPRCPP_VERSION_PATCH

#ifndef LIBPRCPP_VERSION_DATES
    #define LIBPRCPP_VERSION_DATES @LIBPRCPP_VERSION_DATES@
#endif // LIBPRCPP_VERSION_DATES

#ifndef LIBPRCPP_VERSION_STRING
    #define LIBPRCPP_VERSION_STRING "@LIBPRCPP_VERSION_STRING@"
#endif // LIBPRCPP_VERSION_STRING

#endif // LIBPRCPP_CONFIG_H
