#ifndef PRGENT_CONFIG_HH
#define PRGENT_CONFIG_HH

#ifndef PRGENT_VERSION_MAJOR
    #define PRGENT_VERSION_MAJOR @PRGENT_VERSION_MAJOR@
#endif // PRGENT_VERSION_MAJOR

#ifndef PRGENT_VERSION_MINOR
    #define PRGENT_VERSION_MINOR @PRGENT_VERSION_MINOR@
#endif // PRGENT_VERSION_MINOR

#ifndef PRGENT_VERSION_PATCH
    #define PRGENT_VERSION_PATCH @PRGENT_VERSION_PATCH@
#endif // PRGENT_VERSION_PATCH

#ifndef PRGENT_VERSION_DATES
    #define PRGENT_VERSION_DATES @PRGENT_VERSION_DATES@
#endif // PRGENT_VERSION_DATES

#ifndef PRGENT_VERSION_STRING
    #define PRGENT_VERSION_STRING "@PRGENT_VERSION_STRING@"
#endif // PRGENT_VERSION_STRING

#ifndef PRGENT_COMPILER_GNU
    #define PRGENT_COMPILER_GNU @PRGENT_COMPILER_GNU@
#endif // PRGENT_COMPILER_GNU

#ifndef PRGENT_COMPILER_MSVC
    #define PRGENT_COMPILER_MSVC @PRGENT_COMPILER_MSVC@
#endif // PRGENT_COMPILER_MSVC

#ifndef PRGENT_COMPILER_CLANG
    #define PRGENT_COMPILER_CLANG @PRGENT_COMPILER_CLANG@
#endif // PRGENT_COMPILER_CLANG

namespace prgent
{
} // namespace prgent

#endif // PRGENT_CONFIG_HH
